- name: Inject Secrets into config.js
        run: |
          sed -i "s|REPLACE_ME_API_BASE|${{ secrets.VIDEO_API_BASE }}|g" config.js
          sed -i "s|REPLACE_ME_TOKEN|${{ secrets.VIDEO_TOKEN }}|g" config.js